-- MySQL Script generated by MySQL Workbench
-- Tue Jul  6 00:29:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dev_buddy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dev_buddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dev_buddy` DEFAULT CHARACTER SET utf8 ;
USE `dev_buddy` ;

-- -----------------------------------------------------
-- Table `dev_buddy`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_buddy`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dev_buddy`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dev_buddy`.`post` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_user_uid_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_uid`
    FOREIGN KEY (`user_id`)
    REFERENCES `dev_buddy`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
